config/routes.rb
Rails.application.routes.draw do

resources :users do
  member do
    get :following, :followers
  end
end

resources :sessions, only: [:new, :create, :destroy]
resources :microposts,    only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

root 'static_pages#home'
#  get 'users/new'
#  get 'static_pages/home'
#  get 'static_pages/help'
#  get 'static_pages/about'
#  get 'static_pages/contact'

  match '/help',   to: 'static_pages#help',    via: 'get'
  match '/about',  to: 'static_pages#about',   via: 'get'
  get '/contact',  to: 'static_pages#contact', via: 'get'
# match и get  работают одинаково


  match '/signup',  to: 'users#new', 	    via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'




end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	  if signed_in?
		 @micropost  = current_user.microposts.build
		 @feed_items = current_user.feed.paginate(page: params[:page], per_page: 3)
	  end
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_if_signed.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>

	<div class="span8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/static_pages/_home_not_signed.html.erb
<div class="center hero-unit">
	<br>
	<h1>Welcome to the Sample App</h1>
	<h2>
		This is the home page for the
		<a href="http://railstutorial.ru/">Ruby on Rails Tutorial </a>
		  (by Michael Hart) sample application.
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Log in", signin_path, class: "btn btn-large btn-primary" %>
	<br>
	<br>
</div>
<br>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  This is the sample application for the tutorial.
  It's allows users to maintain a blog similar to Twitter.
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<p>
   Ruby on Rails Tutorial about the sample app at the
  <a href="http://myphpdevelop.zz.mu">contact page</a>.
  <ul>
    <li>Contact information #1</li>
    <li>Contact information #2</li>
    <li>Contact information #3</li>
  </ul>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% str = 'For start to use application create a new account (Sign Up) or log in (name5@email.com, 555).
If your want log in with admin privileges, please, contact to web master for
recive ready to account with the appropriate privileges.' %>

<% if signed_in? %>
  <%= render 'static_pages/home_if_signed' %>
<% else %>
  <hr />
    <%= render 'static_pages/home_not_signed' %>
  <hr />
  <b> <%= str %> </b>
<% end %>